import { auth } from "@/auth";
import {
  createPlaylistFromTracks,
  findDiscoveryPlaylists,
  getMe,
  getPlaylistTracks,
  getTopTracks,
  TimeRange,
} from "@/lib/spotify";
import { NextResponse } from "next/server";

export async function POST(req: Request) {
  const session = await auth();
  if (!session?.accessToken) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  const { timeRange, name } = (await req.json()) as {
    timeRange: TimeRange;
    name?: string;
  };

  try {
    const me = await getMe(session.accessToken);
    const { items: topTracks } = await getTopTracks(session.accessToken, timeRange, 25);

    const discoveryPlaylists = await findDiscoveryPlaylists(session.accessToken);
    const similarTracks = (
      await Promise.all(
        discoveryPlaylists.map((p) => getPlaylistTracks(session.accessToken!, p.id, 10))
      )
    ).flat();

    const seen = new Set<string>();
    const uris: string[] = [];
    for (const track of [...topTracks, ...similarTracks]) {
      if (!seen.has(track.uri)) {
        seen.add(track.uri);
        uris.push(track.uri);
      }
    }

    const rangeLabel =
      timeRange === "short_term"
        ? "Last 4 Weeks"
        : timeRange === "medium_term"
        ? "Last 6 Months"
        : "All Time";

    const description = similarTracks.length
      ? `Auto-generated by Sound Track: your ${rangeLabel.toLowerCase()} top tracks plus similar music from your Discover Weekly and Release Radar.`
      : `Auto-generated by Sound Track from your ${rangeLabel.toLowerCase()} top tracks.`;

    const playlist = await createPlaylistFromTracks(
      session.accessToken,
      me.id,
      name?.trim() || `My Top Tracks — ${rangeLabel}`,
      description,
      uris
    );

    return NextResponse.json({
      url: playlist.external_urls?.spotify,
      id: playlist.id,
    });
  } catch (err) {
    console.error(err);
    return NextResponse.json(
      { error: "Failed to create playlist" },
      { status: 500 }
    );
  }
}
