import { auth } from "@/auth";
import {
  createPlaylistFromTracks,
  findDiscoveryPlaylists,
  getPlaylistTracks,
  getTopArtists,
  getTopTracks,
  searchTracksByArtist,
  SpotifyTrack,
  TimeRange,
} from "@/lib/spotify";
import { NextResponse } from "next/server";

export async function POST(req: Request) {
  const session = await auth();
  if (!session?.accessToken) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }
  const accessToken = session.accessToken;

  const { timeRange, name } = (await req.json()) as {
    timeRange: TimeRange;
    name?: string;
  };

  try {
    const [{ items: topTracks }, { items: topArtists }] = await Promise.all([
      getTopTracks(accessToken, timeRange, 25),
      getTopArtists(accessToken, timeRange, 20),
    ]);
    const knownUris = new Set(topTracks.map((t) => t.uri));

    // Best-effort: Spotify's own algorithmic recommendations, if the user
    // has saved Discover Weekly / Release Radar to their library.
    const discoveryPlaylists = await findDiscoveryPlaylists(accessToken);
    const discoveryTracks = (
      await Promise.all(
        discoveryPlaylists.map((p) => getPlaylistTracks(accessToken, p.id, 10))
      )
    ).flat();

    // Always-available fallback: other tracks by artists they already like,
    // picking the LEAST popular ones per artist rather than their biggest
    // hits (search relevance otherwise surfaces exactly what they already
    // know), and excluding anything already in their top tracks.
    const deepCuts = (
      await Promise.all(
        topArtists.map(async (a) => {
          const candidates = (await searchTracksByArtist(accessToken, a.name))
            .filter((t) => !knownUris.has(t.uri))
            .sort((x, y) => (x.popularity ?? 0) - (y.popularity ?? 0));
          return candidates.slice(0, 3);
        })
      )
    ).flat();

    const seen = new Set<string>();
    const uris: string[] = [];
    let newTrackCount = 0;
    for (const track of [...topTracks, ...discoveryTracks, ...deepCuts] as SpotifyTrack[]) {
      if (!seen.has(track.uri)) {
        seen.add(track.uri);
        uris.push(track.uri);
        if (!knownUris.has(track.uri)) newTrackCount++;
      }
    }

    const rangeLabel =
      timeRange === "short_term"
        ? "Last 4 Weeks"
        : timeRange === "medium_term"
        ? "Last 6 Months"
        : "All Time";

    const description = newTrackCount
      ? `Auto-generated by Sound Track: your ${rangeLabel.toLowerCase()} top tracks plus new music from artists you already love.`
      : `Auto-generated by Sound Track from your ${rangeLabel.toLowerCase()} top tracks.`;

    const playlist = await createPlaylistFromTracks(
      accessToken,
      name?.trim() || `My Top Tracks — ${rangeLabel}`,
      description,
      uris
    );

    return NextResponse.json({
      url: playlist.external_urls?.spotify,
      id: playlist.id,
    });
  } catch (err) {
    console.error(err);
    return NextResponse.json(
      { error: "Failed to create playlist" },
      { status: 500 }
    );
  }
}
