import { auth } from "@/auth";
import { createPlaylistFromTracks, getMe, getTopTracks, TimeRange } from "@/lib/spotify";
import { NextResponse } from "next/server";

export async function POST(req: Request) {
  const session = await auth();
  if (!session?.accessToken) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  const { timeRange, name } = (await req.json()) as {
    timeRange: TimeRange;
    name?: string;
  };

  try {
    const me = await getMe(session.accessToken);
    const { items: tracks } = await getTopTracks(session.accessToken, timeRange, 30);
    const uris = tracks.map((t) => t.uri);

    const rangeLabel =
      timeRange === "short_term"
        ? "Last 4 Weeks"
        : timeRange === "medium_term"
        ? "Last 6 Months"
        : "All Time";

    const playlist = await createPlaylistFromTracks(
      session.accessToken,
      me.id,
      name?.trim() || `My Top Tracks — ${rangeLabel}`,
      `Auto-generated by Sound Track from your ${rangeLabel.toLowerCase()} top tracks.`,
      uris
    );

    return NextResponse.json({
      url: playlist.external_urls?.spotify,
      id: playlist.id,
    });
  } catch (err) {
    console.error(err);
    return NextResponse.json(
      { error: "Failed to create playlist" },
      { status: 500 }
    );
  }
}
